### ISSUE TITLE
Usage with pragma message or static_assert?

### ISSUE THREAD

**Issue by Dwood15** [mpark/format#1]
Is it possible to use this library to generate compiler-time strings? I'm just learning (modern) C++ right now, and want to make sure my structs are aligned properly, then if not, generate a message like so:

constexpr (string type here I guess) getStatAssertString(__uint32 size, __uint32 expected) {
//returns formatted string 
}

struct my_invalid {
short foo;
byte bar;
};

static_assert(sizeof(my_invalid) == 0x3, getStatAssertString(sizeof(my_invalid, 0x3);

**Comment by mpark** [comment]
No. `static_assert`s require a string literal, not a "compile-time string" represented within the type system.

**Comment by Dwood15** [comment]
Thank you for the response, sorry to bother.

**Comment by mpark** [comment]
No problem at all 😄
